In [1]:
(ns ground-up.ch4)

nil

- How to increment every number in the vector `[1 2 3]` to produce `[2 3 4]`?

### A direct approach

In [2]:
(def numbers [1 2 3])

#'ground-up.ch4/numbers

In [3]:
(nth numbers 0)

1

In [4]:
(inc (nth numbers 0))

2

### Recursion
- split up a sequence

In [5]:
(first numbers)

1

In [6]:
(rest numbers)

(2 3)

- glue them back

In [7]:
(cons 1 [2 3])

(1 2 3)

- split up a sequence increment the first part, and join them back together

In [8]:
(defn inc-first [nums]
    (cons (inc (first nums))
          (rest nums)))

#'ground-up.ch4/inc-first

In [9]:
(inc-first numbers)

(2 2 3)

In [10]:
;; can't increment the first element of an empty vector
(inc-first [])

Execution error (NullPointerException) at ground-up.ch4/inc-first (REPL:2).
null


class java.lang.NullPointerException: 

In [11]:
(first [])

nil

In [12]:
(clojure.repl/doc if)

-------------------------
if
  (if test then else?)
Special Form
  Evaluates test. If not the singular values nil or false,
  evaluates and yields then, otherwise, evaluates and yields else. If
  else is not supplied it defaults to nil.

  Please see http://clojure.org/special_forms#if
  Evaluates test. If not the singular values nil or false,
  evaluates and yields then, otherwise, evaluates and yields else. If
  else is not supplied it defaults to nil.


nil

In [13]:
(defn inc-first [nums]
    (if (first nums)
        (cons (inc (first nums))
              (rest nums))
        (list)))

#'ground-up.ch4/inc-first

In [14]:
(inc-first [])

()

In [15]:
(inc-first numbers)

(2 2 3)

In [16]:
(defn inc-more [nums]
    (if (first nums)
        (cons (inc (first nums))
              (inc-more (rest nums)))
        (list)))

#'ground-up.ch4/inc-more

In [17]:
(inc-more numbers)

(2 3 4)

key elements in a recursive program
- some part of the problem which has a known solution (base case)
- a relationship which connects one part of the problem to the next (inductive case)

### Generalizing from inc
parametrize our funciton to use any transformation of its elements

In [18]:
(defn transform-all [f xs]
    (if (first xs)
        (cons (f (first xs))
              (transform-all f (rest xs)))
        (list)))

#'ground-up.ch4/transform-all

In [19]:
(transform-all inc [1 2 3 4])

(2 3 4 5)

In [20]:
(transform-all keyword ["bell" "hooks"])

(:bell :hooks)

In [21]:
(transform-all list [:codex :book :manuscript])

((:codex) (:book) (:manuscript))

- we've implemented the `map` function!

In [22]:
(map inc [1 2 3 4])

(2 3 4 5)

In [23]:
(defn expand [f x cnt]
    (when (pos? cnt)
        (cons x (expand f (f x) (dec cnt)))))

#'ground-up.ch4/expand

In [24]:
(expand inc 0 10)

(0 1 2 3 4 5 6 7 8 9)

- we've implemented a simple version of `iterate`!

In [25]:
(take 10 (iterate inc 0))

(0 1 2 3 4 5 6 7 8 9)

In [26]:
;; use iterate to build up strings
(take 5 (iterate (fn [x] (str x "o")) "y"))

("y" "yo" "yoo" "yooo" "yoooo")

In [27]:
(take 10 (repeat "hi"))

("hi" "hi" "hi" "hi" "hi" "hi" "hi" "hi" "hi" "hi")

- `repeat` constructs a sequence where every elemnet is the same
- `repeatedly` calls a function `f` to generate an infinite sequence of values

In [28]:
(repeat 3 :echo)

(:echo :echo :echo)

In [29]:
(take 3 (repeatedly rand))

(0.8706670996757666 0.5105585256980583 0.10756347353215445)

- Note: `rand` is an impure function, since it cannot replaced by the same value every time. It does something different each time it's called

- `range` is a sequence function specifically for numbers
- `cycle` extends a sequence by repeating it forever

In [30]:
(range 5)

(0 1 2 3 4)

In [31]:
(range 2 10)

(2 3 4 5 6 7 8 9)

In [32]:
(range 0 100 5)

(0 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95)

In [33]:
(take 10 (cycle [1 2 3]))

(1 2 3 1 2 3 1 2 3 1)

## Transforming sequences

- If given multiple sequences, `map` calls its function with one element from each sequence in turn, like a zipper

In [34]:
(map (fn [n vehicle] (str "I've got " n " " vehicle "s"))
     [0 200 9]
     ["car" "train" "kiteboard"])

("I've got 0 cars" "I've got 200 trains" "I've got 9 kiteboards")

In [35]:
(map + [1 2 3]
       [4 5 6]
       [7 8 9])

(12 15 18)

- if two sequences has different sizes, `map` stops at the smaller one. This allows us to combine finite and infinite sequences. 

In [36]:
(map (fn [index element] (str index ". " element))
     (iterate inc 0)
     ["erlang" "ruby" "haskell"])

("0. erlang" "1. ruby" "2. haskell")

In [37]:
map-indexed

#function[clojure.core/map-indexed]

In [38]:
;; this is a common operation so we have a built-in function!
(map-indexed (fn [index element] (str index ". " element))
     ["erlang" "ruby" "haskell"])

("0. erlang" "1. ruby" "2. haskell")

In [39]:
;; concatenate sequences
(concat [1 2 3] [:a :b :c] [4 5 6])

(1 2 3 :a :b :c 4 5 6)

In [40]:
(concat '(1 2 3) [:a :b :c] '(4 5 6))

(1 2 3 :a :b :c 4 5 6)

In [41]:
;;interleave
(interleave '(1 2 3) [:a :b :c])

(1 :a 2 :b 3 :c)

In [42]:
;; interpose: insert a specific element between each successive pair in a sequence
(interpose :and [1 2 3 4])

(1 :and 2 :and 3 :and 4)

In [43]:
(reverse [1 2 3])

(3 2 1)

In [44]:
(reverse "woolf")

(\f \l \o \o \w)

In [45]:
;; strings are sequences 
;; each element of a string is a character
;; rejoin characters by `apply str`
(apply str (reverse "woolf"))

"floow"

In [46]:
;; break strings up into sequences
(seq "sato")

(\s \a \t \o)

In [47]:
(sequence "sata")

(\s \a \t \a)

In [48]:
;; randomize the order of a sequence
(shuffle [1 2 3 4])

[1 2 4 3]

### Subsequences
- slicing on sequences

In [49]:
(range 10)

(0 1 2 3 4 5 6 7 8 9)

In [50]:
(take 3 (range 10))

(0 1 2)

In [51]:
(drop 3 (range 10))

(3 4 5 6 7 8 9)

In [52]:
(take-last 3 (range 10))

(7 8 9)

In [53]:
(drop-last 3 (range 10))

(0 1 2 3 4 5 6)

- `take-while` and `drop-while` work just like `take` and `drop`, but use a function to decide when to cut

In [54]:
(take-while pos? [3 2 1 0 -1 10 11])

(3 2 1)

In [55]:
(drop-while odd? [3 5 7 8 9 10 11])

(8 9 10 11)

- cut a sequence in twain by giving it a particular index or a function

In [56]:
(split-at 4 (range 10))

[(0 1 2 3) (4 5 6 7 8 9)]

In [57]:
(split-with number? [1 2 3 :mark 4 5 6 :mark 7])

[(1 2 3) (:mark 4 5 6 :mark 7)]

In [58]:
(filter pos? [1 5 -4 -7 3])

(1 5 3)

In [59]:
;; complement of filter!
(remove string? [1 "turing" :apple '(1)])

(1 :apple (1))

- group a sequence into chunks

In [60]:
(partition 2 [:cats 5 :bats 27 :crocodiles 0])

((:cats 5) (:bats 27) (:crocodiles 0))

In [61]:
(partition-all 3 (range 10))

((0 1 2) (3 4 5) (6 7 8) (9))

In [62]:
(partition-by neg? [1 2 3 2 1 -1 -2 -3 -2 -1 1 2 3])

((1 2 3 2 1) (-1 -2 -3 -2 -1) (1 2 3))

### Collapsing sequences
- number of times each element appears in a sequence

In [63]:
(frequencies [:meow :mrrow :meow :meow])

{:meow 3, :mrrow 1}

- group elements by some function

In [64]:
;; here :first is uased as a function
;; group-by use that function to produce a map of first anmes to lists of people
(group-by :first [{:first "Li"    :last "Zhou"}
                  {:first "Sarah" :last "Lee"}
                  {:first "Sarah" :last "Dunn"}
                  {:first "Li"    :last "O'Toole"}])

{"Li" [{:first "Li", :last "Zhou"} {:first "Li", :last "O'Toole"}], "Sarah" [{:first "Sarah", :last "Lee"} {:first "Sarah", :last "Dunn"}]}

- `reduce`: need to provide a function that takes two arguments
- `reductions` returns a sequence of all the intermediate states

In [65]:
(reduce + [1 2 3 4])

10

In [66]:
(reductions + [1 2 3 4])

(1 3 6 10)

In [67]:
;; start with a defualt value to reduce elements into collections
(reduce conj #{} [:a :b :b :b :a :a])

#{:b :a}

In [68]:
;; this is into!
(into #{} [:a :b :b :b :a :a])

#{:b :a}

In [69]:
(reduce conj {} [[:a 2] [:b 3]])

{:a 2, :b 3}

In [70]:
(into {} [[:a 2] [:b 3]])

{:a 2, :b 3}

- elemented added to a list apprear at the beginning, not the end, we can use this to achieve reverse

In [71]:
(into (list) [1 2 3 4 5])

(5 4 3 2 1)

In [72]:
;; looks like map!
(reduce conj [] [1 2 3 4 5])

[1 2 3 4 5]

In [73]:
;; map is just a special kind of reduce
(defn my-map [f coll]
    (reduce (fn [xs x] (conj xs (f x))) [] coll))

#'ground-up.ch4/my-map

In [74]:
(my-map inc [1 2 3 4])

[2 3 4 5]

In [75]:
(defn my-take-while [f coll]
    (reduce (fn [xs x]
                (if (f x)
                    (conj xs x)
                    (reduced xs))) ;; reduced is used to complete reduction early and skip the rest.
            []
            coll))

#'ground-up.ch4/my-take-while

In [76]:
(my-take-while pos? [1 3 4 -2 3 -5 7])

[1 3 4]

- lazy sequence defers execution to a leter time
- lazy sequences remember their contents, once evaluated, for faster access

In [77]:
(def infseq (map inc (iterate inc 0)))
(realized? infseq)

false

In [78]:
(take 10 infseq)

(1 2 3 4 5 6 7 8 9 10)

In [79]:
(realized? infseq)

true

### Putting it all together
- find the sum of the products of consecutive pairs of the first 1000 odd integers

In [80]:
(def odd-seq (filter odd? (iterate inc 0)))

#'ground-up.ch4/odd-seq

In [81]:
(reduce + (take 1000 (map (fn [[x1 x2]] (* x1 x2)) (partition-all 2 1 odd-seq))))

1335333000

- in the above expression, the part that happens first appears deepest
- It would be nicer to write it in order

In [82]:
(->> 0
    (iterate inc)
    (filter odd?)
    (partition 2 1)
    (map (fn [[x1 x2]]
             (* x1 x2)))
    (take 1000)
    (reduce +))

1335333000

### Problems
- 1. write a funciton to find out is a string is a palindrome

In [83]:
(defn palindrome? [string]
    (= (seq string) (reverse (seq string))))

#'ground-up.ch4/palindrome?

In [84]:
(palindrome? "racecar")

true

In [85]:
(palindrome? "abc")

false

In [86]:
(palindrome? "a")

true

In [87]:
(palindrome? "") ;; why?

false

In [88]:
(seq "")

nil

In [89]:
(reverse (seq ""))

()

In [90]:
;; a better version would be 
(defn palindrome? [string]
    (= (sequence string) (reverse (sequence string))))

#'ground-up.ch4/palindrome?

In [91]:
(palindrome? "")

true

- 2. Find the number of 'c's in "abracadabra"

In [92]:
(count (filter (fn [ch] (= ch \c)) "abracadabra"))

1

- 3. Write your own version of `filter`

In [93]:
(defn my-filter [f coll]
    (reduce (fn [xs x]
                (if (f x)
                    (conj xs x)
                    xs))
            []
            coll))

#'ground-up.ch4/my-filter

In [94]:
(my-filter pos? [1 3 4 -2 3 -5 7])

[1 3 4 3 7]

- 4. Find the first 100 prime numbers

In [95]:
(def x 10)

#'ground-up.ch4/x

In [96]:
(range 2 (inc (Math/sqrt x)))

(2 3 4)

In [97]:
(filter (fn [e] (zero? (rem x e)))
        (range 2 (inc (Math/sqrt x))))

(2)

In [98]:
(nil? (first (filter (fn [e] (zero? (rem x e)))
                     (range 2 (inc (Math/sqrt x))))))

false

In [99]:
(defn prime? [x]
    (nil? (first (filter (fn [e] (zero? (rem x e)))
                         (range 2 (inc (Math/sqrt x)))))))

#'ground-up.ch4/prime?

In [100]:
(prime? 3)

true

In [101]:
(prime? 4)

false

In [102]:
(prime? 2)

false

In [103]:
;; finally we have 
(cons 2 (take 99 (filter prime? (iterate inc 3))))

(2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 101 103 107 109 113 127 131 137 139 149 151 157 163 167 173 179 181 191 193 197 199 211 223 227 229 233 239 241 251 257 263 269 271 277 281 283 293 307 311 313 317 331 337 347 349 353 359 367 373 379 383 389 397 401 409 419 421 431 433 439 443 449 457 461 463 467 479 487 491 499 503 509 521 523 541)

In [104]:
;; or
(conj (take 99 (filter prime? (iterate inc 3))) 2)

(2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 101 103 107 109 113 127 131 137 139 149 151 157 163 167 173 179 181 191 193 197 199 211 223 227 229 233 239 241 251 257 263 269 271 277 281 283 293 307 311 313 317 331 337 347 349 353 359 367 373 379 383 389 397 401 409 419 421 431 433 439 443 449 457 461 463 467 479 487 491 499 503 509 521 523 541)